(in-package :pi-mmal)

(defconstant +mmal-component-default-container-reader+ "container_reader")
(defconstant +mmal-component-default-container-writer+ "container_writer")

(defconstant +mmal-component-default-video-decoder+ "vc.rll.video_decode")
(defconstant +mmal-component-default-video-encoder+ "vc.rll.video_encode")
(defconstant +mmal-component-default-video-renderer+ "vc.rll.video_render")
(defconstant +mmal-component-default-image-decoder+ "vc.rll.image_decode")
(defconstant +mmal-component-default-image-encoder+ "vc.rll.image_encode")
(defconstant +mmal-component-default-camera+ "vc.rll.camera")
(defconstant +mmal-component-default-video-converter+ "vc.video_convert")
(defconstant +mmal-component-default-splitter+ "vc.splitter")
(defconstant +mmal-component-default-scheduler+ "vc.scheduler")
(defconstant +mmal-component-default-video-injecter+ "vc.video_inject")
(defconstant +mmal-component-default-video-splitter+ "vc.rll.video_splitter")
(defconstant +mmal-component-default-audio-decoder+ "none")
(defconstant +mmal-component-default-audio-renderer+ "vc.rll.audio_render")
(defconstant +mmal-component-default-miracast+ "vc.miracast")