(in-package #:pi-mmal)

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.7
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

;;;SWIG wrapper code starts here

(cl:defconstant #.(swig-lispify "MMAL_VERSION_MAJOR" 'constant) 0)
(cl:export '#.(swig-lispify "MMAL_VERSION_MAJOR" 'constant))

(cl:defconstant #.(swig-lispify "MMAL_VERSION_MINOR" 'constant) 1)
(cl:export '#.(swig-lispify "MMAL_VERSION_MINOR" 'constant))

(cl:defconstant #.(swig-lispify "MMAL_VERSION" 'constant)
		(cl:logior (cl:ash 0 16) 1))
(cl:export '#.(swig-lispify "MMAL_VERSION" 'constant))
