(in-package #:pi-mmal)

(cffi:defcenum #.(swig-lispify "MMAL_PORT_TYPE_T" 'enumname)
	(#.(swig-lispify "MMAL_PORT_TYPE_UNKNOWN" 'enumvalue :keyword) #.0)
	#.(swig-lispify "MMAL_PORT_TYPE_CONTROL" 'enumvalue :keyword)
	#.(swig-lispify "MMAL_PORT_TYPE_INPUT" 'enumvalue :keyword)
	#.(swig-lispify "MMAL_PORT_TYPE_OUTPUT" 'enumvalue :keyword)
	#.(swig-lispify "MMAL_PORT_TYPE_CLOCK" 'enumvalue :keyword)
	(#.(swig-lispify "MMAL_PORT_TYPE_INVALID" 'enumvalue :keyword)
           #.#xffffffff))
(cl:export '#.(swig-lispify "MMAL_PORT_TYPE_T" 'enumname))

(cl:defconstant #.(swig-lispify "MMAL_PORT_CAPABILITY_PASSTHROUGH" 'constant)
  #x01)
(cl:export '#.(swig-lispify "MMAL_PORT_CAPABILITY_PASSTHROUGH" 'constant))

(cl:defconstant #.(swig-lispify "MMAL_PORT_CAPABILITY_ALLOCATION" 'constant)
  #x02)
(cl:export '#.(swig-lispify "MMAL_PORT_CAPABILITY_ALLOCATION" 'constant))

(cl:defconstant #.(swig-lispify "MMAL_PORT_CAPABILITY_SUPPORTS_EVENT_FORMAT_CHANGE" 'constant)
  #x04)
(cl:export '#.(swig-lispify "MMAL_PORT_CAPABILITY_SUPPORTS_EVENT_FORMAT_CHANGE" 'constant))

(cffi:defcstruct #.(swig-lispify "MMAL_PORT_T" 'classname)
	(#.(swig-lispify "priv" 'slotname) :pointer)
	(#.(swig-lispify "name" 'slotname) :string)
	(#.(swig-lispify "type" 'slotname)
           #.(swig-lispify "MMAL_PORT_TYPE_T" 'enumname))
	(#.(swig-lispify "index" 'slotname) :unsigned-short)
	(#.(swig-lispify "index_all" 'slotname) :unsigned-short)
	(#.(swig-lispify "is_enabled" 'slotname) :unsigned-int)
	(#.(swig-lispify "format" 'slotname) :pointer)
	(#.(swig-lispify "buffer_num_min" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_size_min" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_alignment_min" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_num_recommended" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_size_recommended" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_num" 'slotname) :unsigned-int)
	(#.(swig-lispify "buffer_size" 'slotname) :unsigned-int)
	(#.(swig-lispify "component" 'slotname) :pointer)
	(#.(swig-lispify "userdata" 'slotname) :pointer)
	(#.(swig-lispify "capabilities" 'slotname) :unsigned-int))
(cl:export '#.(swig-lispify "MMAL_PORT_T" 'classname))

(cl:export '#.(swig-lispify "priv" 'slotname))
(cl:export '#.(swig-lispify "name" 'slotname))
(cl:export '#.(swig-lispify "type" 'slotname))
(cl:export '#.(swig-lispify "index" 'slotname))
(cl:export '#.(swig-lispify "index_all" 'slotname))
(cl:export '#.(swig-lispify "is_enabled" 'slotname))
(cl:export '#.(swig-lispify "format" 'slotname))
(cl:export '#.(swig-lispify "buffer_num_min" 'slotname))
(cl:export '#.(swig-lispify "buffer_size_min" 'slotname))
(cl:export '#.(swig-lispify "buffer_alignment_min" 'slotname))
(cl:export '#.(swig-lispify "buffer_num_recommended" 'slotname))
(cl:export '#.(swig-lispify "buffer_size_recommended" 'slotname))
(cl:export '#.(swig-lispify "buffer_num" 'slotname))
(cl:export '#.(swig-lispify "buffer_size" 'slotname))
(cl:export '#.(swig-lispify "component" 'slotname))
(cl:export '#.(swig-lispify "userdata" 'slotname))
(cl:export '#.(swig-lispify "capabilities" 'slotname))

(cffi:defctype #.(swig-lispify "MMAL_PORT_T" 'typename) (:struct #.(swig-lispify "MMAL_PORT_T" 'classname)))
(cl:export '#.(swig-lispify "MMAL_PORT_T" 'typename))

(cffi:defcfun ("mmal_port_format_commit" #.(swig-lispify "mmal_port_format_commit" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer))
(cl:export '#.(swig-lispify "mmal_port_format_commit" 'function))

(cffi:defctype #.(swig-lispify "MMAL_PORT_BH_CB_T" 'typename) :pointer)
(cl:export '#.(swig-lispify "MMAL_PORT_BH_CB_T" 'typename))

(cffi:defcfun ("mmal_port_enable" #.(swig-lispify "mmal_port_enable" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (cb :pointer))
(cl:export '#.(swig-lispify "mmal_port_enable" 'function))

(cffi:defcfun ("mmal_port_disable" #.(swig-lispify "mmal_port_disable" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer))
(cl:export '#.(swig-lispify "mmal_port_disable" 'function))

(cffi:defcfun ("mmal_port_flush" #.(swig-lispify "mmal_port_flush" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer))
(cl:export '#.(swig-lispify "mmal_port_flush" 'function))

(cffi:defcfun ("mmal_port_parameter_set" #.(swig-lispify "mmal_port_parameter_set" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (param :pointer))
(cl:export '#.(swig-lispify "mmal_port_parameter_set" 'function))

(cffi:defcfun ("mmal_port_parameter_get" #.(swig-lispify "mmal_port_parameter_get" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (param :pointer))
(cl:export '#.(swig-lispify "mmal_port_parameter_get" 'function))

(cffi:defcfun ("mmal_port_send_buffer" #.(swig-lispify "mmal_port_send_buffer" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (buffer :pointer))
(cl:export '#.(swig-lispify "mmal_port_send_buffer" 'function))

(cffi:defcfun ("mmal_port_connect" #.(swig-lispify "mmal_port_connect" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (other_port :pointer))
(cl:export '#.(swig-lispify "mmal_port_connect" 'function))

(cffi:defcfun ("mmal_port_disconnect" #.(swig-lispify "mmal_port_disconnect" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer))
(cl:export '#.(swig-lispify "mmal_port_disconnect" 'function))

(cffi:defcfun ("mmal_port_payload_alloc" #.(swig-lispify "mmal_port_payload_alloc" 'function)) :pointer
  (port :pointer)
  (payload_size :unsigned-int))

(cl:export '#.(swig-lispify "mmal_port_payload_alloc" 'function))
(cffi:defcfun ("mmal_port_payload_free" #.(swig-lispify "mmal_port_payload_free" 'function)) :void
  (port :pointer)
  (payload :pointer))
(cl:export '#.(swig-lispify "mmal_port_payload_free" 'function))

(cffi:defcfun ("mmal_port_event_get" #.(swig-lispify "mmal_port_event_get" 'function)) #.(swig-lispify "MMAL_STATUS_T" 'enumname)
  (port :pointer)
  (buffer :pointer)
  (event :unsigned-int))
(cl:export '#.(swig-lispify "mmal_port_event_get" 'function))
